[devices]
keyboard = "/dev/input/by-path/pci-0000:05:00.3-usb-0:1.2:1.0-event-kbd"
mouse = "/dev/input/by-path/pci-0000:04:00.4-usb-0:2:1.0-event-mouse"

# rules 说明：
#（1）key字段只支持如下的键：
# 键盘左侧的Ctrl键:  KEY_LEFTCTRL
# 键盘右侧的Ctrl键:  KEY_RIGHTCTRL
# 键盘左侧的Alt键:   KEY_LEFTALT
# 键盘右侧的Alt键:   KEY_RIGHTALT
# 键盘左侧的Shift键: KEY_LEFTSHIFT
# 键盘右侧的Shift键: KEY_RIGHTSHIFT
# 键盘左侧的Meta键（也就是Windows键）: KEY_LEFTMETA
# 键盘左侧的Meta键（也就是Windows键）: KEY_RIGHTMETA
# 鼠标侧键之前边侧键: BTN_EXTRA
# 鼠标侧键之后边侧键: BTN_SIDE
#
# （2）rule_type字段支持如下的值：
# 单击：Click
# 双击：DoubleClick
# 按住键并滚动鼠标滚轮：ScrollWheelWithKeyPressed
#
#  （3）action字段说明：
#  支持两种Action：
#  1. Shortcut：描述一个快捷键。当指定的事件发生的时候，按下这个快捷键。有多个键的话有`+`号连接。例如："KEY_LEFTALT+KEY_F7"
#  2. ShortcutWithKeyHolding：描述一个快捷键，这个仅搭配 rule_type = "ScrollWheelWithKeyPressed"使用。当指定的事件发生的时候，
#     按住指定的指定的键然后发出快捷键，每滚动一次滚轮就发出一次快捷键，直到指定的Key被松开。
#     例如:
#      [[rules]]
#      key = "BTN_SIDE"
#      rule_type = "ScrollWheelWithKeyPressed"
#      action = { ShortcutWithKeyHolding = ["KEY_ESC", "KEY_LEFTALT"] } # 左侧是快捷键中除了要被持续按下的那个键之外的键（有多个键的话用`+`号进行连接）；右侧必须上单个键，这个键会被持续按住。
#      这个例子中，当鼠标的侧键中靠后的那个键被按下的时候，如果滚动鼠标滚轮，此时ScrollWheelWithKeyPressed事件发生，
#      开始按下左侧的Alt键并保持这个按下的状态，然后按下Esc键并松开，每滚动一次，就执行一次【按下Esc键并松开】操作，
#      直到鼠标的那个侧键被松开。顺带一提：Alt+Esc在Gnome中被用了切换窗口。

[[rules]]
# 单击`input`中指定的键
key = "BTN_EXTRA"
rule_type = "Click"
action = { Shortcut = "KEY_LEFTALT+KEY_F7" } # BTN_EXTRA 被单击之后，按下 KEY_LEFTALT+KEY_F7 这个快捷键，这个快捷键在Gnome中被用来移动窗口

[[rules]]
key = "BTN_SIDE"
rule_type = "Click"
action = { Shortcut = "KEY_LEFTMETA" } # 单击BTN_SIDE键，转换成单击Meta键（也就是Windows键）

[[rules]]
key = "KEY_LEFTALT"
rule_type = "DoubleClick"
action = { Shortcut = "KEY_LEFTCTRL+KEY_LEFTALT+KEY_V" } # 自定义的快捷键，用来启动vicinae

[[rules]]
key = "KEY_RIGHTALT"
rule_type = "DoubleClick"
action = { Shortcut = "KEY_LEFTCTRL+KEY_LEFTALT+KEY_F" } # 自定义的快捷键，用来启动vicinae的文件搜索

[[rules]]
key = "BTN_SIDE"
rule_type = "DoubleClick"
action = { Shortcut = "KEY_LEFTALT+KEY_F10" } # 切换窗口的最大化/还原状态

[[rules]]
key = "BTN_SIDE"
rule_type = "ScrollWheelWithKeyPressed"
# 模拟Alt+Esc键（在Gnome中用了切换窗口，从首次模拟Alt+Esc开始，Alt键会一直按着，直到松开鼠标的BTN_SIDE键。按下BTN_SIDE键时，每转动一次鼠标滚轮就模拟一次Alt+Esc）
action = { ShortcutWithKeyHolding = ["KEY_ESC", "KEY_LEFTALT"] }
